Fix response parse issue in file upload
renuo/dato-rails pull request #8
Opened 2023-08-22 07:42 UTC by CuddlyBunion341

- File upload methods now return a job_id instead of an upload_id
- The upload_id has to be fetched with the retrieve_job_result method via polling
- Refactored specs to use the example dato model (author)
- Updated readme to reflect changes of bugfix
- Updated changelog

2023-08-22 07:54 UTC, CuddlyBunion341 reviewed
I don't see any problems with the code as of right now, feedback would be nice!

2023-08-23 08:02 UTC, coorasse requested changes
I have some proposals for improvements

2023-08-23 08:02 UTC, coorasse commented on spec/dato/client_spec.rb
> +      response = client.items.create(attributes: {name: "Hello world"}, item_type_id: item_type_id)
why was this changed?

2023-08-23 08:02 UTC, coorasse commented on lib/dato/uploads.rb
> +      {job_id:}
why don't you simply return the `job_id`? I don't think we need to return an hash, since there's just one value returned. the `job_id`

2023-08-23 08:02 UTC, coorasse commented on CHANGELOG.md
> +* Hotfix: Fix a bug that caused file upload to return a 404
where is this fix? I could not find it?

2023-08-23 08:02 UTC, coorasse commented on README.md
> +upload_id = poll_job_result(client, job_id, max_retries: 15)
too complex. let's simplify the example and link the rspec test for more details:
```suggestion
As the file upload is asynchronous, you may need to implement some kind of polling to check if the upload is finished. With the retrieve_job_result method you can retrieve the upload id from the job result.
```ruby
job_id = client.uploads.create_from_file(file.path) # get back a job id
response = client.uploads.retrieve_job_result(job_id).parse # check the status
upload_id = response.dig('data', 'attributes', 'payload', 'data', 'id') # if nil, it's not done yet
```

2023-08-23 09:49 UTC, CuddlyBunion341 commented on spec/dato/client_spec.rb
> +      response = client.items.create(attributes: {name: "Hello world"}, item_type_id: item_type_id)
Because we switched to using dato models present in the CMS clone project. Me and @pandermatt decided on using the author model for testing purposes.

2023-08-23 09:51 UTC, CuddlyBunion341 commented on lib/dato/uploads.rb
> +      {job_id:}
Great question! I honestly have no idea why we decided on returning a hash instead of the value itself...

2023-08-23 10:00 UTC, cb341 commented on CHANGELOG.md
> +* Hotfix: Fix a bug that caused file upload to return a 404
Updated the changelog

2023-08-23 12:13 UTC, pandermatt commented on spec/dato/client_spec.rb
> +      response = client.items.create(attributes: {name: "Hello world"}, item_type_id: item_type_id)
it makes more sense to use the same model for all the tests

2023-08-23 13:47 UTC, coorasse approved these changes
Seems almost good to go. I have two suggestions and then you can directly merge. Thanks

2023-08-23 13:47 UTC, coorasse commented on spec/dato/client_spec.rb
> +      upload_id = response["data"]["attributes"]["payload"]["data"]["id"]
```suggestion
      upload_id = response.dig('data', 'attributes', 'payload', 'data', 'id')
```

2023-08-23 13:47 UTC, coorasse commented on spec/dato/client_spec.rb
> +      expect(response.parse["data"]["attributes"]["picture"]["upload_id"]).to eq(upload_id)
```suggestion
      expect(response.parse.dig('data', 'attributes', 'picture', 'upload_id')).to eq(upload_id)
```

2023-08-23 15:03 UTC, merged